BasicDjango_/apps/app1/urls.py
from django.conf.urls import url

from . import views

app_name='app1'
urlpatterns = [
    url('', views.sender, name = 'sender'),
    ]

BasicDjango_/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Uncomment the next line to enable the admin:
    path('', include('app1.urls')),
    path('admin/', admin.site.urls),
    
]

BasicDjango_/apps/app1/models.py
from django.db import models

class App1(models.Model):


    pass

BasicDjango_/apps/app1/forms.py
from django import forms

class SenderForm(forms.Form):
    LOGIN = forms.EmailField(max_length=30)
    PWD = forms.CharField(widget = forms.PasswordInput())
    WHOM = forms.FileField()
    ATTACH_TPL = forms.FileField(required = False)
    THEME = forms.CharField( max_length=50)
    LETTER = forms.CharField(widget = forms.Textarea(attrs={'cols':30,'rows':10}))

BasicDjango_/apps/app1/views.py
from django.shortcuts import render
import pandas
import smtplib
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email import encoders
from .functions import changeName
from .functions import CreateData
from .forms import SenderForm
import xlrd
import time
import logging
from docxtpl import DocxTemplate

logger=logging.getLogger('django.sender')
MAIL_SERVERS = {'gmail.com': 'smtp.gmail.com:465',
                'miem.hse.ru': 'smtp.gmail.com:465',
                'mail.ru': 'smtp.mail.ru:465',
                'hse.ru': 'smtpnnov.hse.ru:587',
                'yandex.ru': 'smtp.yandex.ru:465',
                'rambler.ru': 'smtp.rambler.ru:465'}

def sender(request):
    resultstr=''
    isError = False
    failedEmails = []
    logger.info("Запуск страницы.")
    submitbutton= request.POST.get("submit")
    if request.method == 'POST':
        form = SenderForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                logger.info("Начало работы программы. Обработка данных из формы...")
                LOGIN = form.cleaned_data.get('LOGIN')
                PWD = form.cleaned_data.get('PWD')
                MESSAGE = form.cleaned_data.get('LETTER')
                THEME = form.cleaned_data.get('THEME')
                MAIL_SERVER = MAIL_SERVERS[LOGIN.split('@')[1]]
                try:
                    logger.info('Cчитывание таблицы...')
                    worksheet = pandas.read_excel(request.FILES['WHOM'], sheet_name=0)
                    if 'ATTACH_TPL' in request.FILES: 
                        tpl = DocxTemplate(request.FILES['ATTACH_TPL'])
                        logger.info('Файл шаблона приклеплён к форме.')
                    else:
                        logger.info('Файл шаблона не приклеплён к форме.')
                    logger.info('Проверка соединения...')
                    server = smtplib.SMTP_SSL(MAIL_SERVER)
                    server.login(LOGIN, PWD)
                    server.quit()
                except xlrd.biffh.XLRDError:
                    isError = True
                    resultstr = 'Неверный формат файла таблицы - работа программы невозможна.'
                    logger.warning(resultstr)
                except ValueError or docx.opc.exceptions.PackageNotFoundError:
                    isError = True
                    resultstr = 'Неверный формат файла шаблона - работа программы невозможна.'
                    logger.warning(resultstr)
                except smtplib.socket.gaierror:
                    isError = True
                    resultstr = "Не удалось соединиться с сервером."
                    logger.warning(resultstr)
                except smtplib.SMTPServerDisconnected:
                    isError = True
                    resultstr = "Разрыв соединения."
                    logger.warning(resultstr)
                except smtplib.SMTPAuthenticationError:
                    isError = True
                    resultstr = "Неверный логин и пароль."
                    logger.warning(resultstr)
                else:
                    logger.info('Все данные введены правильно. Вход прошел успешно. Таблица считана.')
                    MailData = CreateData(worksheet)
                    for mail in MailData:
                        msg = MIMEMultipart()
                        msg['From'] = LOGIN
                        msg['To'] = mail
                        msg['Subject'] = THEME
                        Text = MESSAGE
                        for param in MailData[mail]:
                            Text=Text.replace('{{ ' + param + ' }}', str(MailData[mail][param]))
                        msg.attach(MIMEText(Text, "html"))
                        if 'ATTACH_TPL' in request.FILES: 
                            tpl = DocxTemplate(request.FILES['ATTACH_TPL'])
                            context2 = {param : str(MailData[mail][param]) for param in MailData[mail]}
                            tpl.render(context2)
                            tpl.save('Letter.docx')
                            attachment = 'Letter.docx'
                            attachFile = MIMEBase('application', 'msword')
                            fo = open('Letter.docx', 'rb')
                            attachFile.set_payload(fo.read())
                            fo.close()
                            encoders.encode_base64(attachFile)
                            FileName = request.FILES['ATTACH_TPL'].name.split('.')[0]  + '_To_' + mail.split('@')[0] + '.docx'
                            attachFile.add_header('Content-Disposition', 'attachment', filename=FileName)
                            msg.attach(attachFile)
                            logger.info("Файл для " + mail + " сформирован и приклеплен")
                        try:
                            server = smtplib.SMTP_SSL(MAIL_SERVER)
                        except smtplib.socket.gaierror:
                            logger.warning("Не удалось соединиться с сервером. Письмо для " + mail + " не удалось отправить.")
                            failedEmails.append(mail + '-' + 'не удалось соединиться с сервером.')
                        else:
                            try:
                                server.login(LOGIN, PWD)
                                server.sendmail(LOGIN, mail , msg.as_string())
                            except smtplib.SMTPServerDisconnected:
                                logger.warning("Разрыв соединения - письмо для " + mail + " не удалось отправить.")
                                failedEmails.append(mail + '-' + 'разрыв соединения.')
                            except smtplib.SMTPRecipientsRefused:
                                logger.warning("Неверный адресат - письмо для " + mail + " не удалось отправить.")
                                failedEmails.append(mail + '-' + 'неверный адресат.')
                            else:
                                logger.info("Письмо для " + mail + " отправлено.")
                                try:
                                    server.quit()
                                except smtplib.SMTPServerDisconnected:
                                    logger.warning("Разрыв соединения.")
                        time.sleep(3)
                    logger.info("Программа закончила свою работу.")
            except Exception as e: 
                resultstr='Ошибка: ' + str(e)
            else:
                if not(isError):
                    resultstr = 'Сообщения отправлены'
    else:
        form = SenderForm()
    context= {'form': form, 'submitbutton': submitbutton, 'resultstr':resultstr, 'failedEmails': failedEmails}
    logger.info("Рендеринг страницы.")
    return render(request, 'app1/list.html', context)

BasicDjango_/apps/app1/templates/app1/list.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'app1/Stylesheet1.css' %}">
    <title>Сервис массовой рассылки</title>
</head>

<body>
    <div id="instruction" class="hide">
        <h3>Инструкция:</h3>
        <br>1) Индивидуальное письмо оформляется по указанному шаблону
        <img src={% static "app1/images/extext.png" %} width="300px">
        <br>
        <br>2) Прикрепите таблицу адресатов по указанному шаблону в формате .xlsx
        <img src={% static "app1/images/extable.png" %} width="300px">
        <br>
        <br>3) Прикрепите (если необходимо) вложение для письма в формате .docx по шаблону (см. пункт 1)
        
    </div>  
    
    <div id="a1"> 
        
        <form action = "" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <h1 id="title">Сервис массовой рассылки писем</h1>   
        
        <div class="SenderForm" id="email" >
           <label for="id_LOGIN">Email:</label>
            {{ form.LOGIN }}
            </div>
            <div>
        <div class="SenderForm" id="password">
            <label for="id_PWD">Пароль:</label>
            {{ form.PWD }}
            <div id="button2">  
        <button id="button" onclick="Instruct()">Показать инструкцию</button>
        <script>
            function Instruct() {
                document.getElementById("instruction").classList.toggle("hide");
            }
        </script>
        </div>
        </div>
            </div>
        <div class="SenderForm" id="theme">
            
            <label for="id_THEME">Тема:</label>
            {{ form.THEME }}
        </div>
        <div class="SenderForm" id="letter">
            <div id="menu"></div>
            <div id="sample">
            <script src={% static 'app1/JavaScript.js' %} type="text/javascript"></script>
            <script type="text/javascript">
            bkLib.onDomLoaded(function() {
            
            new nicEditor({fullPanel : true}).panelInstance('id_LETTER');
            
             });
            </script>
            <label for="id_LETTER">Письмо:</label>
            <div id="letter1">
            <textarea name="LETTER" id='id_LETTER' rows="10" ></textarea>
            </div>
            </div>
        </div>
        <div class="SenderForm" id="excel">
        
            <label for="id_WHOM">Файл в формате .xlsx:</label>
            {{ form.WHOM }}
        </div>
        <div class="SenderForm" id="word">
            
            <label for="id_ATTACH_TPL">Файл в формате .docx:</label>
            {{ form.ATTACH_TPL }}
        </div>
        <div id="button1">
        <button id="button" name = "submit" type="submit" value="Sended" >Отправить</button>
        </div>
        </form>
        {% if submitbutton == "Sended" %}
        {% if failedEmails|length > 0 %}
        <h1 id="str">Все сообщения отправлены, кроме:</h1>
        <ol>
        {% for email in failedEmails %}
            <li id="str1">{{ email }}</li>
        {% endfor %}
        </ol>
        {% else %}
        <h1 id="str">{{ resultstr }}</h1>
        {% endif %}
        {% endif %}
        </div>       
</body>
</html>

BasicDjango_/apps/app1/templates/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>{% block title%}Сервис рассылки{% endblock%}</title>
    <link rel="stylesheet" type="text/css" href="Stylesheet1.css">
    
</head>
<body>
    {% block content %} {% endblock%}
</body>
</html>